import { describe, expect, test } from 'bun:test';
import { GmailError } from '../src/lib/server/gmail/error';
import { composeEmail, parseMailbox, rewriteForTestMode, type Email } from '../src/lib/server/gmail/message';

const sender = 'Masterminds <sender@example.com>';
const email: Email = { to: ['student@example.com'], subject: 'Report', body: 'Your report is attached.' };

type Part = { headers: Record<string, string>; body: string; children: Part[] };

// Parse only the MIME shapes generated by our composer, not arbitrary inbound mail.
function readPart(raw: string): Part {
	const split = raw.indexOf('\r\n\r\n');
	expect(split).toBeGreaterThan(-1);
	const headers = Object.fromEntries(raw.slice(0, split).replace(/\r\n[ \t]+/g, ' ').split('\r\n').map((line) => {
		const colon = line.indexOf(':');
		return [line.slice(0, colon).toLowerCase(), line.slice(colon + 1).trim()];
	}));
	const body = raw.slice(split + 4);
	const boundary = /boundary="([^"]+)"/.exec(headers['content-type'] ?? '')?.[1];
	const children = boundary ? body.split(`--${boundary}`).slice(1, -1).map((part) => readPart(part.slice(2, -2))) : [];
	return { headers, body, children };
}

function decodedBytes(part: Part): Buffer {
	if (part.headers['content-transfer-encoding'] === 'base64') return Buffer.from(part.body, 'base64');
	if (part.headers['content-transfer-encoding'] === 'quoted-printable') {
		return Buffer.from(part.body.replace(/=\r\n/g, '').replace(/=([\da-f]{2})/gi, (_, hex) => String.fromCharCode(parseInt(hex, 16))), 'latin1');
	}
	return Buffer.from(part.body);
}

function decodedHeader(value: string): string {
	return value.replace(/(\?=)\s+(=\?)/g, '$1$2').replace(/=\?UTF-8\?([BQ])\?([^?]+)\?=/gi, (_, encoding, content) => {
		if (encoding.toUpperCase() === 'B') return Buffer.from(content, 'base64').toString('utf8');
		return Buffer.from(content.replace(/_/g, ' ').replace(/=([\da-f]{2})/gi, (_: string, hex: string) => String.fromCharCode(parseInt(hex, 16))), 'latin1').toString('utf8');
	});
}

async function invalid(work: () => unknown) {
	try {
		await work();
	} catch (error) {
		expect(error).toBeInstanceOf(GmailError);
		expect((error as GmailError).kind).toBe('bad_input');
		expect(error).not.toHaveProperty('cause');
		return;
	}
	throw new Error('Expected bad_input GmailError.');
}

describe('Gmail mailboxes', () => {
	test('accepts one ASCII mailbox and Unicode or quoted display names without rewriting the address', () => {
		for (const address of ['student@example.com', 'first.last+report@sub.example.com', "o'hara@example.com", 'UPPER@EXAMPLE.COM']) {
			expect(parseMailbox(`  ${address}  `)).toEqual({ name: '', address });
			expect(parseMailbox(`María Menéndez <${address}>`)).toEqual({ name: 'María Menéndez', address });
		}
		expect(parseMailbox('"Menéndez, María" <maria@example.com>')).toEqual({ name: 'Menéndez, María', address: 'maria@example.com' });
		expect(parseMailbox('"María \\"M\\"" <maria@example.com>')).toEqual({ name: 'María "M"', address: 'maria@example.com' });
		expect(parseMailbox('<student@example.com>')).toEqual({ name: '', address: 'student@example.com' });
	});

	test('rejects injected, ambiguous, malformed, and unsupported addresses', async () => {
		for (const value of [
			undefined, null, 1, {}, '', ' ', 'student', '@example.com', 'student@',
			'a@example.com,b@example.com', 'Name a@example.com', 'Name <a@example.com> b@example.com',
			'Group: a@example.com;', 'a@example.com (Name)', 'Name (Comment) <a@example.com>',
			'a..b@example.com', '.a@example.com', 'a.@example.com', 'a@-example.com', 'a@example-.com',
			'a@ex_ample.com', 'a@example..com', 'a@.example.com', 'a@example.com.', 'a@b@c.com',
			'"a b"@example.com', 'á@example.com', 'a@éxample.com', 'a@[127.0.0.1]',
			'Menéndez, María <maria@example.com>', '"Unclosed <a@example.com>',
			'a@example.com\r\nBcc: evil@example.com', 'a@example.com\n', '\ra@example.com',
			'María\tName <a@example.com>', 'a@example.com\0', 'a@example.com\x7f', 'a@example.com\u2028',
			`${'a'.repeat(65)}@example.com`, `a@${'b'.repeat(64)}.com`
		]) await invalid(() => parseMailbox(value));
	});
});

describe('Gmail MIME messages', () => {
	test('composes plain text with all recipient headers, including Bcc for the Gmail API', async () => {
		const part = readPart((await composeEmail({ ...email, cc: ['copy@example.com'], bcc: ['blind@example.com'] }, sender)).toString());
		expect(part.headers.from).toBe(sender);
		expect(part.headers.to).toBe('student@example.com');
		expect(part.headers.cc).toBe('copy@example.com');
		expect(part.headers.bcc).toBe('blind@example.com');
		expect(part.headers.subject).toBe(email.subject);
		expect(part.headers['content-type']).toBe('text/plain; charset=utf-8');
		expect(part.headers['mime-version']).toBe('1.0');
		expect(part.headers['message-id']).toMatch(/^<.+>$/);
		expect(decodedBytes(part).toString().trimEnd()).toBe(email.body!);
		expect(part.children).toEqual([]);
	});

	test('supports HTML-only and nested plain/HTML alternatives', async () => {
		const htmlBody = '<p>Tu informe — María</p>';
		const html = readPart((await composeEmail({ ...email, body: undefined, htmlBody }, sender)).toString());
		expect(html.headers['content-type']).toBe('text/html; charset=utf-8');
		expect(decodedBytes(html).toString().trimEnd()).toBe(htmlBody);
		const alternative = readPart((await composeEmail({ ...email, htmlBody }, sender)).toString());
		expect(alternative.headers['content-type']).toStartWith('multipart/alternative;');
		expect(alternative.children).toHaveLength(2);
		expect(alternative.children[0].headers['content-type']).toStartWith('text/plain;');
		expect(alternative.children[1].headers['content-type']).toStartWith('text/html;');
		expect(decodedBytes(alternative.children[0]).toString()).toBe(email.body!);
		expect(decodedBytes(alternative.children[1]).toString()).toBe(htmlBody);
	});

	test('encodes multilingual subjects, display names, and text without losing Unicode', async () => {
		const subject = 'Certificación de asistencia — María Menéndez ✓ '.repeat(8).trim();
		const body = 'Español: niño, acción, pingüino.\nEnglish: ready.\n日本語: おめでとう';
		const raw = (await composeEmail({ ...email, to: ['"Menéndez, María" <maria@example.com>'], subject, body }, 'Educación <sender@example.com>')).toString();
		const part = readPart(raw);
		expect(decodedHeader(part.headers.subject)).toBe(subject);
		expect(decodedHeader(part.headers.to)).toContain('Menéndez, María');
		expect(decodedHeader(part.headers.from)).toContain('Educación');
		expect(decodedBytes(part).toString().trimEnd().replace(/\r\n/g, '\n')).toBe(body);
		for (const line of raw.split('\r\n')) expect(line.length).toBeLessThan(999);
	});

	for (const htmlBody of [undefined, '<p>Informe</p>']) {
		test(`wraps exact binary attachments in multipart/mixed (${htmlBody ? 'alternative' : 'plain'} body)`, async () => {
			const source = new Uint8Array([99, ...Array.from({ length: 512 }, (_, i) => i % 256), 88]);
			const bytes = source.subarray(1, -1);
			const before = source.slice();
			const part = readPart((await composeEmail({ ...email, htmlBody, attachments: [
				{ filename: 'Certificación María.pdf', bytes, mimeType: 'application/pdf' },
				{ filename: 'empty.bin', bytes: new Uint8Array() }
			] }, sender)).toString());
			expect(part.headers['content-type']).toStartWith('multipart/mixed;');
			expect(part.children).toHaveLength(3);
			expect(part.children[0].headers['content-type']).toStartWith(htmlBody ? 'multipart/alternative;' : 'text/plain;');
			const attachment = part.children[1];
			expect(attachment.headers['content-type']).toStartWith('application/pdf;');
			expect(attachment.headers['content-transfer-encoding']).toBe('base64');
			expect(attachment.headers['content-disposition']).toStartWith('attachment;');
			expect(attachment.headers['content-disposition']).toContain(encodeURIComponent('Certificación María.pdf'));
			expect(decodedBytes(attachment)).toEqual(Buffer.from(bytes));
			for (const line of attachment.body.split('\r\n')) expect(line.length).toBeLessThanOrEqual(76);
			expect(part.children[2].headers['content-type']).toStartWith('application/octet-stream;');
			expect(decodedBytes(part.children[2])).toHaveLength(0);
			expect(source).toEqual(before);
		});
	}

	test('does not accept composer options, attachment paths, URLs, or raw headers from input', async () => {
		const unexpected = {
			...email, from: 'evil@example.com', headers: { 'X-Injected': 'secret' },
			raw: 'Private raw message', envelope: { to: ['evil@example.com'] },
			attachments: [{ filename: 'safe.txt', bytes: new TextEncoder().encode('safe bytes'),
				path: '/nonexistent/private-file', href: 'https://invalid.example/private', raw: 'Private attachment',
				headers: { 'X-Injected': 'secret' } }]
		};
		const raw = (await composeEmail(unexpected, sender)).toString();
		const part = readPart(raw);
		expect(part.headers.from).toBe(sender);
		expect(part.headers.to).toBe(email.to[0]);
		for (const forbidden of ['X-Injected', 'Private raw', 'Private attachment', 'evil@example.com', 'private-file', 'invalid.example']) {
			expect(raw).not.toContain(forbidden);
		}
		expect(decodedBytes(part.children[1]).toString()).toBe('safe bytes');
	});

	test('rejects invalid bodies, subjects, recipient arrays, filenames, types, and bytes', async () => {
		const attachment = { filename: 'report.pdf', bytes: new Uint8Array([1]), mimeType: 'application/pdf' };
		const inputs: unknown[] = [
			null, {}, { ...email, to: [] }, { ...email, to: 'a@example.com' }, { ...email, to: new Array(1) },
			{ ...email, cc: 'a@example.com' }, { ...email, bcc: [null] },
			...['', ' ', 'hello\nBcc: evil@example.com', 'hello\r', 'hello\t', 'hello\0', 'hello\u2029'].map((subject) => ({ ...email, subject })),
			{ ...email, body: '' }, { ...email, body: ' ', htmlBody: '\n' }, { ...email, body: null },
			{ ...email, body: { path: '/private' } }, { ...email, htmlBody: { href: 'https://invalid.example' } },
			{ ...email, attachments: 'report.pdf' }, { ...email, attachments: [null] },
			...['', ' ', '.', '..', '/secret', '..\\secret', 'file.pdf\r\nInjected: yes', 'file.pdf\0'].map((filename) => ({ ...email, attachments: [{ ...attachment, filename }] })),
			...['', 'text', 'text/plain; charset=utf-8', 'application/pdf\n', 'application/pdf\r\nInjected: yes', 'application/pdf\0', 'text/pláin'].map((mimeType) => ({ ...email, attachments: [{ ...attachment, mimeType }] })),
			{ ...email, attachments: [{ ...attachment, bytes: [1, 2] }] },
			{ ...email, attachments: [{ filename: 'private.pdf', path: '/private' }] }
		];
		for (const input of inputs) await invalid(() => composeEmail(input as Email, sender));
	});
});

describe('Gmail test-mode rewrite', () => {
	test('redirects only to sender, includes escaped recipient summary, and leaves input untouched', async () => {
		const original: Email = {
			to: ['"María <tag> & \\"M\\"" <maria@example.com>'], cc: ['copy@example.com'], bcc: ['blind@example.com'],
			subject: 'Report', body: 'Plain report', htmlBody: '<p>HTML report</p>',
			attachments: [{ filename: 'report.pdf', bytes: new Uint8Array([0, 255]) }]
		};
		const before = structuredClone(original);
		const rewritten = rewriteForTestMode(original, sender);
		expect(rewritten.to).toEqual([sender]);
		expect(rewritten.cc).toEqual([]);
		expect(rewritten.bcc).toEqual([]);
		expect(rewritten.subject).toBe('[TEST] Report');
		expect(rewritten.body).toBe(`--- TEST MODE: original recipients ---\nTo: ${original.to[0]}\nCc: copy@example.com\nBcc: blind@example.com\n---\n\nPlain report`);
		expect(rewritten.htmlBody).toContain('&lt;tag&gt; &amp;');
		expect(rewritten.htmlBody).toContain('&quot;');
		expect(rewritten.htmlBody).not.toContain('<tag>');
		expect(rewritten.htmlBody).toEndWith('<p>HTML report</p>');
		const part = readPart((await composeEmail(original, sender, true)).toString());
		expect(part.headers.to).toBe(sender);
		expect(part.headers.cc).toBeUndefined();
		expect(part.headers.bcc).toBeUndefined();
		expect(part.headers.subject).toBe('[TEST] Report');
		expect(part.children[0].headers['content-type']).toStartWith('multipart/alternative;');
		expect(decodedBytes(part.children[1])).toEqual(Buffer.from([0, 255]));
		expect(original).toEqual(before);
	});

	test('adds a plain recipient summary to HTML-only mail and omits empty Cc/Bcc lines', async () => {
		const original = { ...email, body: undefined, htmlBody: '<p>HTML only</p>' };
		const rewritten = rewriteForTestMode(original, sender);
		expect(rewritten.body).toBe('--- TEST MODE: original recipients ---\nTo: student@example.com\n---\n\n');
		const part = readPart((await composeEmail(original, sender, true)).toString());
		expect(part.children).toHaveLength(2);
		expect(decodedBytes(part.children[1]).toString()).toContain('<p>HTML only</p>');
	});

	test('still validates original recipients and required content', async () => {
		await invalid(() => composeEmail({ ...email, to: ['invalid'] }, sender, true));
		await invalid(() => composeEmail({ ...email, body: '' }, sender, true));
	});
});
