import { describe, expect, test } from 'bun:test';
import { Buffer } from 'node:buffer';
import { deflateRawSync, inflateRawSync } from 'node:zlib';
import ExcelJS from 'exceljs';
import {
	MAX_IMPORT_BYTES,
	MAX_IMPORT_ROWS,
	StudentImportFileError,
	parseStudentWorkbook,
	type ImportIssue
} from '../src/lib/server/student-import-file';

type Field = 'firstName' | 'lastName' | 'email' | 'pin';
const fields: Field[] = ['firstName', 'lastName', 'email', 'pin'];
const valid = { firstName: 'María José', lastName: 'O’Neill-Rivera', email: 'student@example.test', pin: '0042' };

function studentRow(overrides: Partial<Record<Field, ExcelJS.CellValue>> = {}): ExcelJS.CellValue[] {
	const values = { ...valid, ...overrides };
	return fields.map((field) => values[field]);
}

function workbookWith(rows: ExcelJS.CellValue[][] = [studentRow()], headers: ExcelJS.CellValue[] = fields): ExcelJS.Workbook {
	const workbook = new ExcelJS.Workbook();
	const worksheet = workbook.addWorksheet('Students');
	worksheet.addRow(headers);
	worksheet.addRows(rows);
	return workbook;
}

function fileFromBytes(bytes: Buffer, name = 'students.xlsx'): File {
	return new File([Uint8Array.from(bytes)], name);
}

async function workbookBytes(workbook: ExcelJS.Workbook): Promise<Buffer> {
	return Buffer.from(await workbook.xlsx.writeBuffer());
}

async function workbookFile(workbook: ExcelJS.Workbook, name = 'students.xlsx'): Promise<File> {
	return fileFromBytes(await workbookBytes(workbook), name);
}

async function parseRows(rows: ExcelJS.CellValue[][], headers: ExcelJS.CellValue[] = fields) {
	return parseStudentWorkbook(await workbookFile(workbookWith(rows, headers)));
}

async function expectFileError(file: File, code: StudentImportFileError['code']) {
	let caught: unknown;
	try { await parseStudentWorkbook(file); } catch (error) { caught = error; }
	expect(caught).toBeInstanceOf(StudentImportFileError);
	expect(caught).toMatchObject({ name: 'StudentImportFileError', code, message: code });
	expect(caught).not.toHaveProperty('cause');
	return caught as StudentImportFileError;
}

// These ZIP helpers mutate only archives generated by ExcelJS (no comments or
// data descriptors), so security tests exercise real XLSX files without a new dependency.
function zipEntries(bytes: Buffer) {
	const end = bytes.length - 22;
	let cursor = bytes.readUInt32LE(end + 16);
	const entries: { name: string; local: number; central: number; header: Buffer; directory: Buffer; packed: Buffer; method: number }[] = [];
	for (let index = 0; index < bytes.readUInt16LE(end + 10); index++) {
		const nameSize = bytes.readUInt16LE(cursor + 28), extraSize = bytes.readUInt16LE(cursor + 30), commentSize = bytes.readUInt16LE(cursor + 32);
		const local = bytes.readUInt32LE(cursor + 42);
		const start = local + 30 + bytes.readUInt16LE(local + 26) + bytes.readUInt16LE(local + 28);
		const next = cursor + 46 + nameSize + extraSize + commentSize;
		entries.push({ name: bytes.subarray(cursor + 46, cursor + 46 + nameSize).toString(), local, central: cursor,
			header: Buffer.from(bytes.subarray(local, start)), directory: Buffer.from(bytes.subarray(cursor, next)),
			packed: bytes.subarray(start, start + bytes.readUInt32LE(cursor + 20)), method: bytes.readUInt16LE(cursor + 10) });
		cursor = next;
	}
	return entries;
}

function crc32(bytes: Buffer): number {
	let value = 0xffffffff;
	for (const byte of bytes) {
		value ^= byte;
		for (let bit = 0; bit < 8; bit++) value = (value >>> 1) ^ ((value & 1) ? 0xedb88320 : 0);
	}
	return (value ^ 0xffffffff) >>> 0;
}

function rewriteZipEntry(bytes: Buffer, name: string, rewrite: (content: Buffer) => Buffer): Buffer {
	const entries = zipEntries(bytes);
	expect(entries.some((entry) => entry.name === name)).toBe(true);
	const localParts: Buffer[] = [], directoryParts: Buffer[] = [];
	let offset = 0;
	for (const entry of entries) {
		if (entry.name === name) {
			const content = rewrite(entry.method === 8 ? inflateRawSync(entry.packed) : entry.packed);
			entry.packed = entry.method === 8 ? deflateRawSync(content) : content;
			const checksum = crc32(content);
			entry.header.writeUInt32LE(checksum, 14);
			entry.header.writeUInt32LE(entry.packed.length, 18);
			entry.header.writeUInt32LE(content.length, 22);
			entry.directory.writeUInt32LE(checksum, 16);
			entry.directory.writeUInt32LE(entry.packed.length, 20);
			entry.directory.writeUInt32LE(content.length, 24);
		}
		entry.directory.writeUInt32LE(offset, 42);
		localParts.push(entry.header, entry.packed);
		directoryParts.push(entry.directory);
		offset += entry.header.length + entry.packed.length;
	}
	const directory = Buffer.concat(directoryParts), end = Buffer.from(bytes.subarray(-22));
	end.writeUInt32LE(directory.length, 12);
	end.writeUInt32LE(offset, 16);
	return Buffer.concat([...localParts, directory, end]);
}

async function rewriteWorksheet(rewrite: (xml: string) => string): Promise<File> {
	const bytes = await workbookBytes(workbookWith());
	return fileFromBytes(rewriteZipEntry(bytes, 'xl/worksheets/sheet1.xml', (content) => Buffer.from(rewrite(content.toString()))));
}

describe('student workbook headers', () => {
	test('exports the agreed limits and preserves workbook row numbers', async () => {
		expect(MAX_IMPORT_BYTES).toBe(2 * 1024 * 1024);
		expect(MAX_IMPORT_ROWS).toBe(100);
		expect(await parseRows([studentRow()])).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
	});

	for (const headers of [
		['firstName', 'lastName', 'email', 'pin'],
		[' FIRST_NAME ', 'LAST NAME', ' E-Mail ', 'PIN'],
		['Nómbre', 'Apellídos', 'Correo_Electrónico', 'Código PIN'],
		['Nombre de pila', 'Primer Apellido', 'Dirección de correo electrónico', 'Clave PIN'],
		['Given Name', 'Surname', 'Email Address', 'PIN (4 digits)']
	]) {
		test(`accepts English/Spanish aliases: ${headers.join(', ')}`, async () => {
			expect(await parseRows([studentRow()], headers)).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
		});
	}

	test('accepts arbitrary header order and ignores extra columns and their objects', async () => {
		const headers = ['Notes', 'PIN', 'Correo', 'Apellido', 'Nombre', 'Other'];
		const rows: ExcelJS.CellValue[][] = [[{ formula: '1+1', result: 2 }, '0042', ' STUDENT@EXAMPLE.TEST ', valid.lastName, valid.firstName, { error: '#N/A' }]];
		expect(await parseRows(rows, headers)).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
	});

	for (const headers of [
		['firstName', 'lastName', 'email'],
		['firstName', 'lastName', 'email', 'Password'],
		['firstName', 'lastName', 'email', 'pin', 'Correo Electrónico'],
		['firstName', 'lastName', 'email', 'pin', ' First_Name '],
		[{ formula: '"firstName"', result: 'firstName' }, 'lastName', 'email', 'pin']
	] satisfies ExcelJS.CellValue[][]) {
		test(`rejects missing, duplicate, or formula headers: ${JSON.stringify(headers)}`, async () => {
			await expectFileError(await workbookFile(workbookWith([studentRow()], headers)), 'headers');
		});
	}

	test('does not search later rows for headings', async () => {
		const workbook = new ExcelJS.Workbook();
		const worksheet = workbook.addWorksheet('Students');
		worksheet.getRow(2).values = fields;
		worksheet.getRow(3).values = studentRow();
		await expectFileError(await workbookFile(workbook), 'headers');
	});
});

describe('student workbook values', () => {
	test('trims names and raw email without losing accents or punctuation', async () => {
		const result = await parseRows([studentRow({ firstName: `  ${valid.firstName}  `, lastName: ` ${valid.lastName} `, email: ' STUDENT@EXAMPLE.TEST ' })]);
		expect(result).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
	});

	test('preserves four-digit text PINs and intentionally pads Excel numeric PINs', async () => {
		const pins = ['0042', '0000', '9999', 0, 7, 42, 100, 9999];
		const result = await parseRows(pins.map((pin, index) => studentRow({ pin, email: `student${index}@example.test` })));
		expect(result.issues).toEqual([]);
		expect(result.students.map((student) => student.pin)).toEqual(['0042', '0000', '9999', '0000', '0007', '0042', '0100', '9999']);
	});

	test('accepts names of 100 characters and a mailbox of 254 characters', async () => {
		const email = `${'a'.repeat(64)}@${'b'.repeat(63)}.${'c'.repeat(63)}.${'d'.repeat(61)}`;
		expect(email).toHaveLength(254);
		const result = await parseRows([studentRow({ firstName: 'á'.repeat(100), lastName: 'B'.repeat(100), email })]);
		expect(result.students).toHaveLength(1);
		expect(result.issues).toEqual([]);
	});

	test('skips blank and space-only rows, including styled blanks, but retains physical row numbers', async () => {
		const workbook = workbookWith([]), worksheet = workbook.worksheets[0];
		worksheet.getRow(2).values = ['', ' ', null, '   '];
		worksheet.getRow(3).values = studentRow();
		worksheet.getRow(7).height = 20;
		worksheet.getRow(9).values = studentRow({ email: 'other@example.test', pin: 0 });
		expect(await parseStudentWorkbook(await workbookFile(workbook))).toEqual({
			students: [{ row: 3, ...valid }, { row: 9, ...valid, email: 'other@example.test', pin: '0000' }], issues: []
		});
	});

	test('a row with only an extra-column value is not totally blank', async () => {
		expect(await parseRows([[null, null, null, null, 'note']], [...fields, 'Notes'])).toEqual({
			students: [], issues: [{ row: 2, code: 'name' }, { row: 2, code: 'email' }, { row: 2, code: 'pin' }]
		});
	});

	const invalidFields: { field: Field; value: ExcelJS.CellValue; code: ImportIssue['code'] }[] = [
		...['', ' ', 'a'.repeat(101), 'Ana\n', '\tAna', 'Ana\u0085', 'Ana\u2028', 'Ana\u2029', 42, null].map((value) => ({ field: 'firstName' as const, value, code: 'name' as const })),
		{ field: 'lastName', value: 'a'.repeat(101), code: 'name' },
		{ field: 'lastName', value: null, code: 'name' },
		...['', 'bad@@example.test', 'a..b@example.test', 'a@-example.test', 'a@ex_ample.test',
			'Name <student@example.test>', '<student@example.test>', '"Name" <student@example.test>',
			'a@example.test,b@example.test', 'Group: a@example.test;', 'a@example.test (Name)',
			'a@example.test\r\nBcc: other@example.test', 'a@example.test\n', 'á@example.test',
			`${'a'.repeat(65)}@example.test`, `${'a'.repeat(64)}@${'b'.repeat(63)}.${'c'.repeat(63)}.${'d'.repeat(62)}`, 42, null
		].map((value) => ({ field: 'email' as const, value, code: 'email' as const })),
		...['', '42', '042', '00042', ' 0042', '0042 ', '00 42', '00\n42', '００４２', '004a', -1, 10000, 4.2, Infinity, null
		].map((value) => ({ field: 'pin' as const, value, code: 'pin' as const }))
	];
	for (const { field, value, code } of invalidFields) {
		test(`reports ${code} for invalid ${field}: ${JSON.stringify(value)}`, async () => {
			expect(await parseRows([studentRow({ [field]: value })])).toEqual({ students: [], issues: [{ row: 2, code }] });
		});
	}

	test('rejects booleans, dates, errors, rich text, hyperlinks and cached formula results in every required field', async () => {
		const values: ((field: Field) => ExcelJS.CellValue)[] = [
			() => true,
			() => false,
			() => new Date('2000-01-01T00:00:00Z'),
			() => ({ error: '#DIV/0!' }),
			(field) => ({ richText: [{ text: valid[field] }] }),
			(field) => ({ text: valid[field], hyperlink: 'https://example.test' }),
			(field) => ({ formula: '"cached"', result: valid[field] }),
			() => ({ formula: '1+1', result: 42 }),
			() => ({ formula: '1+1' })
		];
		const rows: ExcelJS.CellValue[][] = [];
		for (const field of fields) {
			for (const value of values) rows.push(studentRow({ email: `student${rows.length}@example.test`, [field]: value(field) }));
		}
		const result = await parseRows(rows);
		expect(result).toEqual({ students: [], issues: rows.map((_, index) => ({ row: index + 2, code: 'cell' })) });
		expect(JSON.stringify(result.issues)).not.toContain(valid.pin);
		expect(result.issues.every((issue) => Object.keys(issue).sort().join(',') === 'code,row')).toBe(true);
	});

	test('rejects shared formula cells even with a valid cached numeric PIN', async () => {
		const result = await parseRows([
			studentRow({ pin: { formula: '42', result: 42 } }),
			studentRow({ email: 'other@example.test', pin: { sharedFormula: 'D2', result: 42 } })
		]);
		expect(result).toEqual({ students: [], issues: [{ row: 2, code: 'cell' }, { row: 3, code: 'cell' }] });
	});

	test('does not trust a cached result behind an empty formula that ExcelJS would discard', async () => {
		const file = await rewriteWorksheet((xml) => xml.replace(/(<c r="D2"[^>]*>)/, '$1<f/>'));
		expect(await parseStudentWorkbook(file)).toEqual({ students: [], issues: [{ row: 2, code: 'cell' }] });
	});

	test('does not skip a formula-only row with no cached value', async () => {
		const result = await parseRows([[{ formula: '1+1' }, null, null, null]]);
		expect(result.students).toEqual([]);
		expect(result.issues).toEqual([{ row: 2, code: 'cell' }, { row: 2, code: 'name' }, { row: 2, code: 'email' }, { row: 2, code: 'pin' }]);
	});

	test('reports all invalid field categories without including any raw PIN', async () => {
		const result = await parseRows([[null, null, 'not-an-email', 'sensitive-invalid-pin']]);
		expect(result).toEqual({ students: [], issues: [{ row: 2, code: 'name' }, { row: 2, code: 'email' }, { row: 2, code: 'pin' }] });
		expect(JSON.stringify(result)).not.toContain('sensitive-invalid-pin');
	});

	test('flags every normalized duplicate, including otherwise invalid rows, and excludes all of them', async () => {
		const result = await parseRows([
			studentRow({ email: 'Student@Example.Test' }),
			studentRow({ email: ' STUDENT@EXAMPLE.TEST ' }),
			studentRow({ firstName: 0 }),
			studentRow({ email: 'unique@example.test' })
		]);
		expect(result).toEqual({ students: [{ row: 5, ...valid, email: 'unique@example.test' }], issues: [
			{ row: 2, code: 'duplicate' }, { row: 3, code: 'duplicate' }, { row: 4, code: 'name' }, { row: 4, code: 'duplicate' }
		] });
	});
});

describe('student workbook limits and file errors', () => {
	test('accepts exactly 100 nonblank data rows with blank gaps', async () => {
		const rows = Array.from({ length: MAX_IMPORT_ROWS }, (_, index) => studentRow({ email: `student${index}@example.test` }));
		rows.splice(50, 0, [], []);
		const result = await parseRows(rows);
		expect(result.students).toHaveLength(MAX_IMPORT_ROWS);
		expect(result.students.at(-1)?.row).toBe(103);
		expect(result.issues).toEqual([]);
	});

	test('rejects 101 nonblank rows even when every row is invalid', async () => {
		await expectFileError(await workbookFile(workbookWith(Array.from({ length: 101 }, () => [0, 0, 0, 0]))), 'limit');
	});

	test('accepts row 1000 and column 50, including styled blank rows/columns', async () => {
		const workbook = workbookWith([]), worksheet = workbook.worksheets[0];
		worksheet.getRow(1000).values = studentRow();
		worksheet.getColumn(50).width = 12;
		worksheet.getCell('AX1000').value = 'ignored';
		expect(await parseStudentWorkbook(await workbookFile(workbook))).toEqual({ students: [{ row: 1000, ...valid }], issues: [] });
	});

	test('rejects actual and styled blank rows past 1000', async () => {
		for (const blank of [false, true]) {
			const workbook = workbookWith(), worksheet = workbook.worksheets[0];
			if (blank) worksheet.getRow(1001).height = 20;
			else worksheet.getCell('A1001').value = 'far away';
			await expectFileError(await workbookFile(workbook), 'limit');
		}
	});

	test('rejects actual and styled blank columns past 50', async () => {
		for (const blank of [false, true]) {
			const workbook = workbookWith(), worksheet = workbook.worksheets[0];
			if (blank) worksheet.getColumn(51).width = 12;
			else worksheet.getCell('AY2').value = 'far away';
			await expectFileError(await workbookFile(workbook), 'limit');
		}
	});

	for (const [label, rewrite] of [
		['sparse row index', (xml: string) => xml.replace('<row r="2"', '<row r="2147483647"')],
		['sparse cell row', (xml: string) => xml.replace('r="A2"', 'r="A2147483647"')],
		['sparse cell column', (xml: string) => xml.replace('r="A2"', 'r="XFD2"')],
		['declared dimension', (xml: string) => xml.replace(/<dimension[^>]*\/>/, '<dimension ref="A1:XFD1048576"/>')],
		['styled column range', (xml: string) => xml.replace('<sheetData>', '<cols><col min="1" max="2147483647" width="12"/></cols><sheetData>')],
		['blank row span', (xml: string) => xml.replace('spans="1:4"', 'spans="1:2147483647"')],
		['merge range', (xml: string) => xml.replace('</sheetData>', '</sheetData><mergeCells><mergeCell ref="A1:XFD1048576"/></mergeCells>')],
		['data validation range', (xml: string) => xml.replace('</sheetData>', '</sheetData><dataValidations><dataValidation sqref="A1:A1048576"/></dataValidations>')]
	] as const) {
		test(`rejects hostile ${label} before ExcelJS can allocate it`, async () => {
			await expectFileError(await rewriteWorksheet(rewrite), 'limit');
		});
	}

	test('rejects duplicate row/cell coordinates and entity-obscured sparse coordinates', async () => {
		for (const rewrite of [
			(xml: string) => xml.replace('r="2"', 'r="1"'),
			(xml: string) => xml.replace('r="B2"', 'r="A2"'),
			(xml: string) => xml.replace('r="A2"', 'r="A&#49;0000000"')
		]) await expectFileError(await rewriteWorksheet(rewrite), 'file');
	});

	test('bounds workbook sheet IDs and named ranges independently of worksheet dimensions', async () => {
		const bytes = await workbookBytes(workbookWith());
		for (const rewrite of [
			(xml: string) => xml.replace('sheetId="1"', 'sheetId="2147483647"'),
			(xml: string) => xml.replace('</sheets>', '</sheets><definedNames><definedName name="hostile">Students!$A$1:$D$1048576</definedName></definedNames>')
		]) {
			const changed = rewriteZipEntry(bytes, 'xl/workbook.xml', (content) => Buffer.from(rewrite(content.toString())));
			await expectFileError(fileFromBytes(changed), 'limit');
		}
	});

	test('allows an ordinary bounded named range', async () => {
		const workbook = workbookWith();
		workbook.definedNames.add('Students!$A$1:$D$2', 'ImportCells');
		expect(await parseStudentWorkbook(await workbookFile(workbook))).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
	});

	for (const name of ['students.xls', 'students.XLS', 'students.csv', 'students.xlsm', 'students.xlsx.exe', 'students', 'students.xlsx ']) {
		test(`rejects unsupported extension: ${name}`, async () => {
			await expectFileError(await workbookFile(workbookWith(), name), 'file');
		});
	}

	test('accepts uppercase .XLSX without relying on the browser MIME type', async () => {
		expect(await parseStudentWorkbook(await workbookFile(workbookWith(), 'Students.XLSX'))).toEqual({ students: [{ row: 2, ...valid }], issues: [] });
	});

	test('rejects an empty upload and workbooks without any nonblank data rows', async () => {
		await expectFileError(new File([], 'students.xlsx'), 'empty');
		await expectFileError(await workbookFile(workbookWith([])), 'empty');
		await expectFileError(await workbookFile(workbookWith([[], ['', ' ', null, '']])), 'empty');
		const workbook = new ExcelJS.Workbook();
		workbook.addWorksheet('Students');
		await expectFileError(await workbookFile(workbook), 'empty');
	});

	test('rejects oversized uploads without reading them, but does not label the exact byte limit oversized', async () => {
		const file = new File([new Uint8Array(MAX_IMPORT_BYTES + 1)], 'students.xlsx');
		let read = false;
		Object.defineProperty(file, 'arrayBuffer', { value: async () => { read = true; throw new Error('must not read'); } });
		await expectFileError(file, 'limit');
		expect(read).toBe(false);
		await expectFileError(new File([new Uint8Array(MAX_IMPORT_BYTES)], 'students.xlsx'), 'file');
	});

	test('rejects malformed, truncated, and legacy binary workbooks with safe errors', async () => {
		const bytes = await workbookBytes(workbookWith());
		for (const malformed of [Buffer.from('sensitive-invalid-pin'), Buffer.from([0xd0, 0xcf, 0x11, 0xe0]), bytes.subarray(0, bytes.length - 10)]) {
			const error = await expectFileError(fileFromBytes(malformed), 'file');
			expect(JSON.stringify(error)).not.toContain('sensitive-invalid-pin');
		}
		await expectFileError(await rewriteWorksheet((xml) => xml.replace('</worksheet>', '')), 'file');
	});

	test('rejects zero or multiple worksheets, including hidden extra sheets', async () => {
		await expectFileError(await workbookFile(new ExcelJS.Workbook()), 'file');
		for (const state of ['visible', 'hidden', 'veryHidden'] as const) {
			const workbook = workbookWith();
			workbook.addWorksheet('Other', { state });
			await expectFileError(await workbookFile(workbook), 'file');
		}
	});

	test('rejects encrypted flags, unsupported compression, ZIP64, and incorrect ZIP checksums', async () => {
		const original = await workbookBytes(workbookWith());
		const entry = zipEntries(original).find((entry) => entry.name === 'xl/worksheets/sheet1.xml')!;
		const mutations: ((bytes: Buffer) => void)[] = [
			(bytes) => { bytes.writeUInt16LE(1, entry.central + 8); bytes.writeUInt16LE(1, entry.local + 6); },
			(bytes) => { bytes.writeUInt16LE(99, entry.central + 10); bytes.writeUInt16LE(99, entry.local + 8); },
			(bytes) => { bytes.writeUInt16LE(45, entry.central + 6); bytes.writeUInt16LE(45, entry.local + 4); },
			(bytes) => { bytes.writeUInt32LE(0xffffffff, entry.central + 24); },
			(bytes) => { bytes.writeUInt16LE(0xffff, bytes.length - 12); bytes.writeUInt16LE(0xffff, bytes.length - 14); },
			(bytes) => { bytes.writeUInt32LE(0, entry.central + 16); bytes.writeUInt32LE(0, entry.local + 14); },
			(bytes) => { bytes.writeUInt32LE(0, entry.local); }
		];
		for (const mutate of mutations) {
			const bytes = Buffer.from(original);
			mutate(bytes);
			await expectFileError(fileFromBytes(bytes), 'file');
		}
	});

	test('bounds aggregate expanded ZIP bytes even when the upload is very small', async () => {
		const bytes = rewriteZipEntry(await workbookBytes(workbookWith()), 'docProps/core.xml', () => Buffer.alloc(10 * 1024 * 1024, 'x'));
		expect(bytes.length).toBeLessThan(MAX_IMPORT_BYTES);
		await expectFileError(fileFromBytes(bytes), 'limit');
	});

	test('bounds actual inflation rather than trusting forged expanded ZIP sizes', async () => {
		const bytes = rewriteZipEntry(await workbookBytes(workbookWith()), 'docProps/core.xml', () => Buffer.alloc(11 * 1024 * 1024, 'x'));
		const entry = zipEntries(bytes).find((entry) => entry.name === 'docProps/core.xml')!;
		bytes.writeUInt32LE(1, entry.central + 24);
		bytes.writeUInt32LE(1, entry.local + 22);
		await expectFileError(fileFromBytes(bytes), 'limit');
	});
});
